version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: leaderboard_user
      POSTGRES_PASSWORD: leaderboard_password
      POSTGRES_DB: leaderboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leaderboard_user -d leaderboard_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
